### ISSUE TITLE
THE FLIPPER ZERO CAN RUN DOOM

### ISSUE THREAD

**Issue by ethan-solis** [zvolchak/can-it-run-doom#23]
https://www.vice.com/en/article/qjkjxw/you-can-now-play-doom-in-the-tamagotchi-like-hacking-device#:~:text=Therefore%20I%20did%20an%20attempt,on%20their%20Github%20project%20page.

**Comment by zvolchak** [comment]
Thanks for reporting this one!

Added it to the DB here:
https://canitrundoom.org?id=1028

(Pull Request for reference: https://github.com/zvolchak/can-it-run-doom/pull/24)
