### ISSUE TITLE
Pagination broken on some pages

### ISSUE THREAD

**Issue by xythobuz** [zvolchak/can-it-run-doom#36]
On the first page the pagination bar is missing the entry "3":

![image](https://github.com/zvolchak/can-it-run-doom/assets/557828/2566cf58-9c81-4c01-86c6-1e59e37851d8)

Page 2 and 3 show all entries, as expected.

Page 4 is also broken.

This is with both Chromium and Firefox on Linux.

**Comment by zvolchak** [comment]
> On the first page the pagination bar is missing the entry "3"

Thanks for reminding me about this one. Its partially intentional. I need to add `...` icon to indicate there are more pages.

> Page 4 is also broken.

What is broken for you on that page? Nothing stands out to me currently on that page.

**Comment by xythobuz** [comment]
Hm, I see.

Page 4:

![image](https://github.com/zvolchak/can-it-run-doom/assets/557828/48a754bc-89e8-491d-90d1-771ae29a66a6)


Page 2 & 3 look like this:

![image](https://github.com/zvolchak/can-it-run-doom/assets/557828/15c15492-8da3-42a2-a103-3d8259bc3a6a)

**Comment by zvolchak** [comment]
Yep same idea here. Should be `...` icon or something similar. Nonetheless - will try to fix it one as soon as I can. Thanks for reporting this!

**Comment by zvolchak** [comment]
This should be fixed now: https://github.com/zvolchak/can-it-run-doom/pull/37
Currently, with 4 pages it will show all of them. But once there are 5 and more, it will use "..." icon to hide furthest pages.

Thanks again for reporting this issue!
