### ISSUE TITLE
Addition: Candy Bar of Doom

### ISSUE THREAD

**Issue by TheKitty** [zvolchak/can-it-run-doom#38]
https://blog.adafruit.com/2022/10/21/parents-please-carefully-inspect-your-kids-halloween-candy/
https://youtu.be/6V_ofcX9cic

great site!

**Comment by zvolchak** [comment]
Haha! 
Thanks for reporting this one! I'll add it to the db as soon as I'll have a moment.

Cheers!

**Comment by zvolchak** [comment]
Added Candy Bar of Doom to the database (along with a few other cool items):
https://github.com/zvolchak/can-it-run-doom/pull/39
