### ISSUE TITLE
Kodak camera port is incorrectly attributed to someone else

### ISSUE THREAD

**Issue by plaidpants** [zvolchak/can-it-run-doom#41]
I was one of the first to port DOOM to something else. I first released this port on July 7th 2000.

https://plaidpants.github.io/mamed/news2000.htm

**Comment by zvolchak** [comment]
Hi!
My apologies for not crediting you correctly for that port and Thanks for reporting this issue!

[I've changed](https://github.com/zvolchak/can-it-run-doom/pull/42) the Author to your name and updated the date of the port - making it The oldest known port in my database thus far!

I've kept the YouTube source pointing to LGR video about the port - but please let me know if that might be confusing, as far as who the actual author is, or if you spot any other issues with the entry:
https://canitrundoom.org?id=1009
